#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from pydantic import ValidationError

from app.models.schemas import FavoriteSyncRequest, MarkerSyncRequest, SummarySyncRequest
from app.services.favorite_service import FavoriteService
from app.services.marker_service import MarkerService
from app.services.summary_service import SummaryService


def main() -> int:
    parser = argparse.ArgumentParser(description="Import local sync bundle into markers/summaries storage")
    parser.add_argument(
        "--bundle",
        default="data/inbox/sync_bundle.json",
        help="Path to bundle JSON generated by andalus-taraweeh/scripts/sync_reels_engine.py --bundle-out",
    )
    args = parser.parse_args()

    bundle_path = Path(args.bundle).expanduser().resolve()
    if not bundle_path.exists():
        raise SystemExit(f"Bundle not found: {bundle_path}")

    payload = json.loads(bundle_path.read_text(encoding="utf-8"))
    days = payload.get("days", []) if isinstance(payload, dict) else []
    summaries = payload.get("summaries", []) if isinstance(payload, dict) else []
    favorites = payload.get("favorites", []) if isinstance(payload, dict) else []

    marker_service = MarkerService()
    summary_service = SummaryService()
    favorite_service = FavoriteService()

    day_results: list[dict] = []
    for day_item in days:
        try:
            req = MarkerSyncRequest(**day_item)
        except ValidationError as exc:
            day_results.append(
                {
                    "day": day_item.get("day") if isinstance(day_item, dict) else None,
                    "status": "error",
                    "error": str(exc),
                }
            )
            continue
        resp = marker_service.sync(req)
        day_results.append({"day": req.day, "status": "ok", "marker_count": resp.marker_count})

    summary_result: dict
    if summaries:
        try:
            summary_req = SummarySyncRequest(summaries=summaries)
            summary_resp = summary_service.sync(summary_req)
            summary_result = {"status": "ok", "count": summary_resp.count}
        except ValidationError as exc:
            summary_result = {"status": "error", "error": str(exc)}
    else:
        summary_result = {"status": "skipped", "reason": "no summaries in bundle"}

    favorite_result: dict
    if favorites:
        try:
            favorite_req = FavoriteSyncRequest(items=favorites, full_refresh=True)
            favorite_resp = favorite_service.sync(favorite_req)
            favorite_result = {"status": "ok", "count": favorite_resp.count}
        except ValidationError as exc:
            favorite_result = {"status": "error", "error": str(exc)}
    else:
        favorite_result = {"status": "skipped", "reason": "no favorites in bundle"}

    print(
        json.dumps(
            {
                "status": "ok",
                "bundle": str(bundle_path),
                "days": day_results,
                "summaries": summary_result,
                "favorites": favorite_result,
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
